import { PrimeNG } from "primeng/config";

export const AllRoutes={

    //Auth Routes//
    login:'/auth/login',
    signUp:'/auth/sign-up',
    forgotPassword:'/auth/forgot-password',
    changePassword:'/auth/change-password',
    lockScreen: "/lock-screen",

    //Features Routes//
    index:'/index',
    chat: "/application/chat",
    voiceCall: "/application/calls/voice-call",
    videoCall: "/application/calls/video-call",
    calendar: "/application/calendar",
    email: "/application/email",
    emailCompose: "/application/email-compose",
    emailDetails: "/application/email-details",
    contacts: "/application/contacts",
    contactList: "/application/contacts-list",
    invoiceList: "/application/invoice/invoice-list",
    invoiceDetails: "/application/invoice/invoice-details",
    addInvoice:"/application/invoice/add-invoice",
    editInvoice:"/application/invoice/edit-invoice",
    todo: "/application/todo",
    notes: "/application/notes",
    kanbanView: "/application/kanban-view",
    fileManager: "/application/file-manager",
    socialFeed: "/application/social-feed",
    searchResult: "/application/search-result",
    
    //layouts//
    layoutMini: "/layout-mini",
    layoutHoverview: "/layout-hoverview",
    layoutHidden: "/layout-hidden",
    layoutFullwidth: "/layout-fullwidth",
    layoutRtl: "/layout-rtl",
    layoutDark: "/layout-dark",

    // Healthcare
    patients: "/patients/patients",
    editPatient: "/patients/edit-patients",
    allPatientsList: "/patients/all-patients-list",
    patientSearch: "/patients/patient-search",
    patientDetails: "/patients/patient-details",
    patientDetailsAppointment:"/patients/patient-details-appointments",
    patientDetailsVitalSign:"/patients/patient-details-vital-signs",
    patientetailsVisitHistory:"/patients/patient-details-visit-history",
    patientetailsLabResults:"/patients/patient-details-lab-results",
    patientdetailsPrescription:"/patients/patient-details-prescription",
    patientetailsMedicalHistory:"/patients/patient-details-medical-history",
    patientetailsDocuments:"/patients/patient-details-documents",
    patientetailsInsurance:"/patients/patient-details-insurance",
    patientDetailsVisitHistory:"/patients/patient-details-visit-history",
    patientDetailsLabResults:"/patient-details-lab-results",
    addPatient: "/patients/add-patient",
    doctors: "/doctors/doctors",
    allDoctorsList:"/doctors/all-doctors-list",
    addDoctor: "/doctors/add-doctor",
    editDoctor: "/doctors/edit-doctor",
    doctorDetails: "/doctors/doctor-details",
    allDoctors: "/doctors/all-doctors",
    appointments: "/appointments/appointment",
    appointmentConsultation:"/appointments/appointment-consultation",
    appointmentCalendar: "/appointments/appointment-calendar",
    transactions: "/appointments/transactions",
    transactionDetails: "/appointments/transaction-details",
    visits: "/visits",
    startVisits: "/start-visits",
    labResults: "/laboratory/lab-results",
    medicalResults: "/laboratory/medical-results",
    pharmacy: "/pharmacy",
    requests: "/requests",
    manageInvoicesDetails:"/manage-invoices-details",
    manageEditInvoices:"/manage-edit-invoices",
    manageAddInvoices:"/manage-add-invoices",
  


    // MANAGE
    staff: "/staffs",
    notifications: "/notifications",
    messages: "/messages",
    manageInvoices: "/manage-invoices",
    generalSettings: "/settings/general-settings",
    securitySettings: "/settings/security-settings",
    preferencesSettings: "/settings/preferences-settings",
    appearanceSettings: "/settings/appearance-settings",
    notificationsSettings: "/settings/notifications-settings",
    userPermissionsSettings: "/settings/user-permissions-settings",
    plansBillingsSettings: "/settings/plans-billings-settings",
    permissionSettings:"/settings/permission-settings",

    // PAGES

   
    error404: "/error-404",
    error500: "/error-500",
    starterPage: "/pages/starter-page",
    comingSoon: "/coming-soon",
    underMaintenance: "/under-maintenance",
    privacyPolicy: "/pages/privacy-policy",
    termsAndConditions: "/pages/terms-and-conditions",

    //UI Interface Routes//
    uiAccordion:'/base-ui/ui-accordion',
    uiAlerts:'/base-ui/ui-alerts',
    uiAvatar:'/base-ui/ui-avatar',
    uiBadges:'/base-ui/ui-badges',
    uiBreadcrumb:'/base-ui/ui-breadcrumb',
    uiButtons:'/base-ui/ui-buttons',
    uiButtonsGroup:'/base-ui/ui-buttons-group',
    uiCards:'/base-ui/ui-cards',
    uiCarousel:'/base-ui/ui-carousel',
    uiCollapse:'/base-ui/ui-collapse',
    uiDropdowns:'/base-ui/ui-dropdowns',
    uiRatio:'/base-ui/ui-ratio',
    uiGrid:'/base-ui/ui-grid',
    uiImages:'/base-ui/ui-images',
    uiLinks:'/base-ui/ui-links',
    uiListGroup:'/base-ui/ui-list-group',
    uiModals:'/base-ui/ui-modals',
    uiOffcanvas:'/base-ui/ui-offcanvas',
    uiPagination:'/base-ui/ui-pagination',
    uiPlaceholders:'/base-ui/ui-placeholders',
    uiPopovers:'/base-ui/ui-popovers',
    uiProgress:'/base-ui/ui-progress',
    uiScrollspy:'/base-ui/ui-scrollspy',
    uiSpinner:'/base-ui/ui-spinner',
    uiTabs:'/base-ui/ui-nav-tabs',
    uiToasts:'/base-ui/ui-toasts',
    uiTooltips:'/base-ui/ui-tooltips',
    uiTypography:'/base-ui/ui-typography',
    uiUtilities:'/base-ui/ui-utilities',

      // UI Interface - Advanced UI
    uiDragula: "/advanced-ui/ui-drag-drop",
    uiClipboard: "/advanced-ui/ui-clipboard",
    uiRangeSlider: "/advanced-ui/ui-rangeslider",
    uiLightbox: "/advanced-ui/ui-lightbox",
    uiRating: "/advanced-ui/ui-rating",
    uiScrollbar: "/advanced-ui/ui-scrollbar",
    uiDragDrop: "/advanced-ui/ui-drag-drop",

        // UI Interface - Forms
    formBasicInputs: "/forms/form-element/form-basic-inputs",
    formCheckboxRadios: "/forms/form-element/form-checkbox-radios",
    formInputGroups: "/forms/form-element/form-input-groups",
    formGridGutters: "/forms/form-element/form-grid-gutters",
    formMask: "/forms/form-element/form-mask",
    formFileupload: "/forms/form-element/form-fileupload",
    formHorizontal: "/forms/layouts/form-horizontal",
    formVertical: "/forms/layouts/form-vertical",
    formFloatingLabels: "/forms/layouts/form-floating-labels",
    formValidation: "/forms/form-validation",
    formSelect: "/forms/form-select",
    formWizard: "/forms/form-wizard",
    formPickers: "/forms/form-pickers",
    formEditors: "/forms/form-editors",

    // UI Interface - Tables
    tablesBasic: "/tables/tables-basic",
    dataTables: "/tables/data-tables",

    // UI Interface - Charts
    chartApex: "/charts/chart-apex",
    primeNG: "/charts/prime-ng",


    // UI Interface - Icons
    iconFontawesome: "/icons/icon-fontawesome",
    iconTabler: "/icons/icon-tabler",
    iconBootstrap: "/icons/icon-bootstrap",
    iconRemix: "/icons/icon-remix",
    iconFeather: "/icons/icon-feather",
    iconIonic: "/icons/icon-ionic",
    iconMaterial: "/icons/icon-material",
    iconPe7: "/icons/icon-pe7",
    iconSimpleline: "/icons/icon-simpleline",
    iconThemify: "/icons/icon-themify",
    iconWeather: "/icons/icon-weather",
    iconTypicon: "/icons/icon-typicon",
    iconFlag: "/icons/icon-flag",

    widgets: "/widgets",
}